import { chromium } from '@playwright/test';
const out = process.env.TEMP + '\\shots2';
const browser = await chromium.launch();
let page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto('http://localhost:5199/', { waitUntil: 'networkidle' });
await page.waitForTimeout(3500);
await page.screenshot({ path: `${out}\\d-hero-b.png` });
await page.evaluate(() => { document.documentElement.style.scrollBehavior='auto'; window.scrollTo(0, 420); });
await page.waitForTimeout(900);
await page.screenshot({ path: `${out}\\d-hero-scrolled.png` });
await page.close();
page = await browser.newPage({ viewport: { width: 390, height: 844 } });
await page.goto('http://localhost:5199/', { waitUntil: 'networkidle' });
await page.waitForTimeout(3500);
await page.evaluate(() => { document.documentElement.style.scrollBehavior='auto'; document.getElementById('premium')?.scrollIntoView(); window.scrollBy(0, 120); });
await page.waitForTimeout(1800);
await page.screenshot({ path: `${out}\\m-pricing-b.png` });
console.log('mobile page height now:', await page.evaluate(() => document.documentElement.scrollHeight));
await browser.close();
