services:
  - type: web
    name: achivii-api
    runtime: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install --include=dev && npm run use:postgres && npx prisma db push && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
      - key: JWT_SECRET
        generateValue: true
